import { useEffect, useState } from 'react'
import { Check, ChevronDown, LoaderCircle, ShieldCheck } from 'lucide-react'
import { getRepositorySettings, saveRepositorySecret, saveRepositorySettings, verifyRepository, type Repo } from '../lib/auth'

export function RepositorySettingsPanel({repo}:{repo:Repo}){
  const [open,setOpen]=useState(false),[loading,setLoading]=useState(false),[message,setMessage]=useState('')
  const [previewUrl,setPreviewUrl]=useState(''),[visibility,setVisibility]=useState<'private'|'public'>('private'),[loginPath,setLoginPath]=useState('/login')
  const [emailLabel,setEmailLabel]=useState('Email'),[passwordLabel,setPasswordLabel]=useState('Password'),[submitName,setSubmitName]=useState('Log in'),[successText,setSuccessText]=useState('')
  const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[configured,setConfigured]=useState<string[]>([])
  useEffect(()=>{if(!open)return;getRepositorySettings(repo.fullName).then(settings=>{if(!settings)return;setPreviewUrl(settings.previewUrl);setVisibility(settings.reportVisibility);setLoginPath(settings.loginPath??'/login');setConfigured(settings.secretNames);const fills=settings.loginSteps.filter(step=>step.action==='fillSecret');setEmailLabel(fills[0]?.label??'Email');setPasswordLabel(fills[1]?.label??'Password');setSubmitName(settings.loginSteps.find(step=>step.action==='click')?.name??'Log in');setSuccessText(settings.loginSteps.find(step=>step.action==='assertText')?.text??'')}).catch(()=>setMessage('Could not load settings.'))},[open,repo.fullName])
  async function save(){setLoading(true);setMessage('');try{if(email)await saveRepositorySecret(repo.fullName,'TEST_EMAIL',email);if(password)await saveRepositorySecret(repo.fullName,'TEST_PASSWORD',password);const loginSteps=loginPath?[{action:'fillSecret',label:emailLabel,secretRef:'TEST_EMAIL'},{action:'fillSecret',label:passwordLabel,secretRef:'TEST_PASSWORD'},{action:'click',role:'button',name:submitName},...(successText?[{action:'assertText',text:successText}]:[])]:[];const result=await saveRepositorySettings(repo.fullName,{previewUrl,enabled:true,reportVisibility:visibility,loginPath:loginPath||undefined,loginSteps});setConfigured(result.settings.secretNames);setEmail('');setPassword('');setMessage('Settings saved.')}catch{setMessage('Could not save settings.')}finally{setLoading(false)}}
  async function verify(){setLoading(true);setMessage('Testing preview and login…');try{const result=await verifyRepository(repo.fullName);setMessage(result.verified?'Preview and login verified.':result.error??'Verification failed.')}catch{setMessage('Verification failed.')}finally{setLoading(false)}}
  return <div className="border-t border-black/5 pt-3">
    <button type="button" onClick={()=>setOpen(value=>!value)} className="flex w-full items-center gap-2 text-left text-xs font-semibold text-[#3D4577]">
      <ShieldCheck size={14}/><span>Test settings</span><ChevronDown size={14} className={`ml-auto transition-transform ${open?'rotate-180':''}`}/>
    </button>
    {open&&<div className="mt-4 grid gap-4 border-t border-black/5 pt-4">
      <label className="grid gap-1.5 text-xs font-medium text-[#3D4577]">Staging URL<input className="fb-input" type="url" required value={previewUrl} onChange={event=>setPreviewUrl(event.target.value)} placeholder="https://staging.example.com"/></label>
      <div className="grid gap-3 sm:grid-cols-2">
        <label className="grid gap-1.5 text-xs font-medium text-[#3D4577]">Login path<input className="fb-input" value={loginPath} onChange={event=>setLoginPath(event.target.value)} placeholder="/login"/></label>
        <label className="grid gap-1.5 text-xs font-medium text-[#3D4577]">Report access<select className="fb-input" value={visibility} onChange={event=>setVisibility(event.target.value as 'private'|'public')}><option value="private">Private</option><option value="public">Public link</option></select></label>
      </div>
      <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-xs font-medium text-[#3D4577]">Email field label<input className="fb-input" value={emailLabel} onChange={event=>setEmailLabel(event.target.value)}/></label><label className="grid gap-1.5 text-xs font-medium text-[#3D4577]">Password field label<input className="fb-input" value={passwordLabel} onChange={event=>setPasswordLabel(event.target.value)}/></label></div>
      <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-xs font-medium text-[#3D4577]">Test email<input className="fb-input" type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder={configured.includes('TEST_EMAIL')?'Configured — enter to replace':'qa@example.com'}/></label><label className="grid gap-1.5 text-xs font-medium text-[#3D4577]">Test password<input className="fb-input" type="password" value={password} onChange={event=>setPassword(event.target.value)} placeholder={configured.includes('TEST_PASSWORD')?'Configured — enter to replace':'Write-only secret'}/></label></div>
      <div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-xs font-medium text-[#3D4577]">Submit button name<input className="fb-input" value={submitName} onChange={event=>setSubmitName(event.target.value)}/></label><label className="grid gap-1.5 text-xs font-medium text-[#3D4577]">Success text<input className="fb-input" value={successText} onChange={event=>setSuccessText(event.target.value)} placeholder="Dashboard"/></label></div>
      {message&&<p role="status" className="m-0 text-xs text-[#545C8C]">{message}</p>}
      <div className="flex flex-wrap gap-2"><button type="button" disabled={loading||!previewUrl} onClick={save} className="inline-flex items-center gap-2 rounded-full bg-[#131B4D] px-4 py-2 text-xs font-semibold text-white disabled:opacity-50">{loading?<LoaderCircle size={13} className="animate-spin"/>:<Check size={13}/>}Save</button><button type="button" disabled={loading||!previewUrl} onClick={verify} className="rounded-full border border-black/10 bg-white px-4 py-2 text-xs font-semibold text-[#131B4D] disabled:opacity-50">Verify login</button></div>
    </div>}
  </div>
}
