import { useEffect, useMemo, useState } from 'react'
import { Check, ChevronLeft, CircleAlert, Clipboard, ExternalLink, Film, LoaderCircle, TerminalSquare } from 'lucide-react'
import { Link } from '@tanstack/react-router'
import { getArtifactUrl, type Artifact, type Finding, type RunReport } from '../lib/auth'

const terminal=new Set(['completed','failed','superseded'])
const badge:Record<string,string>={confirmed:'bg-[#FCEAEC] text-[#9D2635]',flaky:'bg-[#FFF4D8] text-[#8A5A00]',inconclusive:'bg-[#EEF2FE] text-[#3D4577]',completed:'bg-[#EAF6EF] text-[#246E47]',failed:'bg-[#FCEAEC] text-[#9D2635]'}

export function RunReportView({report,shareToken,onRefresh}:{report:RunReport;shareToken?:string;onRefresh?:()=>void}){
  const {run}=report,findings=report.findings??run.findings??[],artifacts=report.artifacts??run.artifacts??[],results=report.results??run.results??[],plan=report.plan??run.plan
  const sorted=useMemo(()=>[...findings].sort((a,b)=>rank(a)-rank(b)),[findings]),[selected,setSelected]=useState(sorted[0]?.id),finding=sorted.find(item=>item.id===selected)??sorted[0]
  const [urls,setUrls]=useState<Record<string,string>>({}),[copied,setCopied]=useState('')
  const proof=finding?artifacts.filter(item=>item.testId===finding.testId):[]
  useEffect(()=>{if(!onRefresh||terminal.has(run.status))return;const id=setInterval(onRefresh,2000);return()=>clearInterval(id)},[onRefresh,run.status])
  useEffect(()=>{for(const artifact of proof)if(!urls[artifact.id])getArtifactUrl(run.id,artifact.id,shareToken).then(value=>setUrls(current=>({...current,[artifact.id]:value.url}))).catch(()=>undefined)},[finding?.id])
  const video=proof.find(item=>item.kind==='video'),screenshot=proof.find(item=>item.kind==='screenshot'),trace=proof.find(item=>item.kind==='trace')
  async function copy(agent:string){if(!finding?.repairPrompt)return;await copyText(finding.repairPrompt);setCopied(agent);setTimeout(()=>setCopied(''),1600)}
  return <div className="min-h-screen bg-[#F3F5FA] text-[#131B4D]">
    <header className="border-b border-[#DDE2EF] bg-[#F9FAFD]"><div className="mx-auto flex max-w-[1480px] items-center gap-3 px-4 py-4 sm:gap-4 sm:px-7"><Link to="/dashboard" className="inline-flex shrink-0 items-center gap-1 whitespace-nowrap text-xs font-semibold text-[#545C8C] no-underline sm:gap-2"><ChevronLeft size={15}/>Runs</Link><span className="h-4 w-px shrink-0 bg-[#DDE2EF]"/><span className="min-w-0 truncate text-sm font-semibold">{run.repository??run.targetUrl}{run.pullRequest?` · PR #${run.pullRequest}`:''}</span><span className={`ml-auto shrink-0 whitespace-nowrap rounded-full px-2 py-1 text-[9px] font-bold uppercase tracking-[.1em] sm:px-3 sm:text-[11px] sm:tracking-[.12em] ${badge[run.status]??'bg-[#E8EBF4] text-[#545C8C]'}`}>{run.status}</span></div></header>
    <main className="mx-auto max-w-[1480px] px-4 py-7 sm:px-7">
      <section className="grid gap-5 border-b border-[#DDE2EF] pb-7 lg:grid-cols-[1fr_auto]">
        <div><p className="fb-mono m-0 text-[10px] tracking-[.18em] text-[#737BA6] uppercase">Run proof</p><h1 className="m-0 mt-2 text-2xl font-semibold tracking-[-.02em]">{findings.length?`${findings.filter(item=>item.classification==='confirmed').length} confirmed failures`:'No confirmed failures'}</h1><p className="mt-2 max-w-3xl text-sm text-[#545C8C]">Tested <a href={run.targetUrl} target="_blank" rel="noreferrer" className="font-medium text-[#2B4BF2]">{run.targetUrl}</a>{run.headSha?` at ${run.headSha.slice(0,8)}`:''}. Fixed staging target cannot prove deployed SHA.</p></div>
        <dl className="grid grid-cols-3 gap-x-7 text-right"><div><dt className="text-[10px] uppercase tracking-[.14em] text-[#8A92C0]">Tests</dt><dd className="m-0 mt-1 text-xl font-semibold">{results.length}</dd></div><div><dt className="text-[10px] uppercase tracking-[.14em] text-[#8A92C0]">Failed</dt><dd className="m-0 mt-1 text-xl font-semibold">{results.filter(item=>item.status==='failed').length}</dd></div><div><dt className="text-[10px] uppercase tracking-[.14em] text-[#8A92C0]">Duration</dt><dd className="m-0 mt-1 text-xl font-semibold">{formatMs(results.reduce((sum,item)=>sum+item.durationMs,0))}</dd></div></dl>
      </section>
      {!terminal.has(run.status)&&<div className="mt-6 flex items-center gap-3 border border-[#CCD5F5] bg-[#EEF2FE] px-4 py-3 text-sm text-[#3D4577]"><LoaderCircle size={16} className="animate-spin"/>Run in progress: {run.status}</div>}
      {run.error&&<div className="mt-6 flex items-start gap-3 border border-[#F0C7CD] bg-[#FCEAEC] px-4 py-3 text-sm text-[#8D2735]"><CircleAlert size={17}/><span>{run.error}</span></div>}
      <div className="mt-7 grid min-h-[640px] border border-[#DDE2EF] bg-[#F9FAFD] lg:grid-cols-[300px_minmax(0,1fr)_360px]">
        <aside className="border-b border-[#DDE2EF] lg:border-r lg:border-b-0"><div className="border-b border-[#DDE2EF] px-4 py-3 text-[10px] font-bold uppercase tracking-[.16em] text-[#737BA6]">Failures · {sorted.length}</div>{sorted.length?<div>{sorted.map(item=><button key={item.id} onClick={()=>setSelected(item.id)} className={`block w-full border-b border-[#E7EAF2] px-4 py-4 text-left transition ${finding?.id===item.id?'bg-[#EEF2FE]':'hover:bg-[#F3F5FA]'}`}><span className={`rounded px-2 py-1 text-[9px] font-bold uppercase tracking-[.12em] ${badge[item.classification??'']??badge.inconclusive}`}>{item.classification??'reported'}</span><strong className="mt-3 block text-sm leading-snug">{item.title}</strong><span className="mt-1 block text-xs text-[#737BA6]">{item.category??'functional'} · {item.severity}</span></button>)}</div>:<div className="px-5 py-8 text-sm text-[#545C8C]"><Check size={18} className="mb-3 text-[#2F8F5B]"/>No failure evidence in this run.</div>}</aside>
        <section className="min-w-0 border-b border-[#DDE2EF] p-5 lg:border-r lg:border-b-0 sm:p-7">{finding?<><div className="flex flex-wrap items-start gap-3"><div><p className="fb-mono m-0 text-[10px] tracking-[.14em] text-[#737BA6] uppercase">Selected failure</p><h2 className="m-0 mt-2 text-xl font-semibold">{finding.title}</h2></div></div><div className="mt-6 aspect-video overflow-hidden bg-[#11172E]">{video&&urls[video.id]?<video controls className="h-full w-full" src={urls[video.id]}/>:screenshot&&urls[screenshot.id]?<img className="h-full w-full object-contain" src={urls[screenshot.id]} alt={`Failure screenshot for ${finding.title}`}/>:<div className="flex h-full items-center justify-center gap-2 text-sm text-[#BFC6E5]"><Film size={18}/>Proof media unavailable</div>}</div>
          <div className="mt-6 grid gap-6 xl:grid-cols-2"><Detail label="Expected" value={finding.expected}/><Detail label="Actual" value={finding.actual??finding.details}/></div><div className="mt-7"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#737BA6]">Reproduction</p><ol className="mt-3 grid gap-2 pl-5 text-sm text-[#3D4577]">{finding.reproduction?.map((step,index)=><li key={index}><code className="break-all text-xs">{step}</code></li>)}</ol></div>{(finding.consoleErrors?.length||finding.networkErrors?.length)?<div className="mt-7 grid gap-5 xl:grid-cols-2"><EvidenceList label="Console errors" values={finding.consoleErrors}/><EvidenceList label="Failed requests" values={finding.networkErrors}/></div>:null}{trace&&urls[trace.id]&&<a href={urls[trace.id]} className="mt-6 inline-flex items-center gap-2 text-xs font-semibold text-[#2B4BF2]" target="_blank" rel="noreferrer"><ExternalLink size={14}/>Download Playwright trace</a>}</>:<div className="flex h-full items-center justify-center text-sm text-[#737BA6]">Select a finding to inspect proof.</div>}</section>
        <aside className="min-w-0 bg-[#F5F6FA] p-5"><div className="flex items-center gap-2"><TerminalSquare size={16}/><h2 className="m-0 text-sm font-semibold">Repair prompt</h2></div><p className="mt-2 text-xs leading-relaxed text-[#737BA6]">One evidence-rich prompt. Copy into your coding agent.</p><pre className="mt-4 max-h-[420px] overflow-auto whitespace-pre-wrap border border-[#DDE2EF] bg-[#FFFFFF] p-4 text-[11px] leading-relaxed text-[#30385F]">{finding?.repairPrompt??'Prompt appears after failure analysis completes.'}</pre><div className="mt-3 grid gap-2">{['Cursor','Claude','Codex'].map(agent=><button key={agent} disabled={!finding?.repairPrompt} onClick={()=>copy(agent)} className="inline-flex items-center justify-center gap-2 rounded-md bg-[#131B4D] px-3 py-2.5 text-xs font-semibold text-white disabled:opacity-40">{copied===agent?<Check size={14}/>:<Clipboard size={14}/>} {copied===agent?'Copied':`Copy for ${agent}`}</button>)}</div></aside>
      </div>
      <section className="mt-7 grid gap-7 lg:grid-cols-2"><div><h2 className="text-sm font-semibold">Generated tests</h2><div className="mt-3 border border-[#DDE2EF] bg-[#F9FAFD]">{plan?.tests?.map(test=><details key={test.id} className="border-b border-[#E7EAF2] last:border-0"><summary className="cursor-pointer px-4 py-3 text-sm font-medium">{test.title}</summary><pre className="m-0 overflow-auto bg-[#F3F5FA] p-4 text-[11px]">{JSON.stringify(test.steps,null,2)}</pre></details>)}</div></div><div><h2 className="text-sm font-semibold">Pipeline timeline</h2><ol className="mt-3 border border-[#DDE2EF] bg-[#F9FAFD]">{run.events?.map((event,index)=><li key={`${event.at}-${index}`} className="flex gap-4 border-b border-[#E7EAF2] px-4 py-3 text-xs last:border-0"><time className="fb-mono text-[#8A92C0]">{new Date(event.at).toLocaleTimeString()}</time><strong className="uppercase tracking-[.1em]">{event.status}</strong><span className="text-[#737BA6]">{event.message}</span></li>)}</ol></div></section>
    </main>
  </div>
}
const rank=(finding:Finding)=>finding.classification==='confirmed'?0:finding.classification==='flaky'?1:2
const formatMs=(ms:number)=>ms>60_000?`${(ms/60_000).toFixed(1)}m`:`${(ms/1000).toFixed(1)}s`
function Detail({label,value}:{label:string;value?:string}){return <div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#737BA6]">{label}</p><p className="mt-2 text-sm leading-relaxed text-[#3D4577]">{value??'Not recorded'}</p></div>}
function EvidenceList({label,values}:{label:string;values?:string[]}){return <div><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#737BA6]">{label}</p><ul className="mt-2 grid gap-1 pl-4 text-xs text-[#3D4577]">{values?.length?values.map((value,index)=><li key={index} className="break-all">{value}</li>):<li>None captured</li>}</ul></div>}
async function copyText(value:string){try{await navigator.clipboard.writeText(value)}catch{const input=document.createElement('textarea');input.value=value;input.style.position='fixed';input.style.opacity='0';document.body.appendChild(input);input.select();document.execCommand('copy');input.remove()}}
