import { createHmac } from 'node:crypto'
import { describe,expect,it } from 'vitest'
import { createApp } from '../app.js'; import { loadConfig } from '../config.js'; import { InMemoryEventBus } from '../events.js'; import { MemoryRunStore } from '../store.js'; import { MemoryUserStore } from '../users.js'; import { createCatalog } from './catalog.js'; import { MemoryBillingStore } from './store.js'
const catalog=createCatalog({starterProductId:'p1',scaleProductId:'p2',starterCredits:100,scaleCredits:500})
const config=loadConfig({BILLING_ENABLED:'true',DODO_API_KEY:'x',DODO_WEBHOOK_KEY:'x',DODO_STARTER_PRODUCT_ID:'p1',DODO_SCALE_PRODUCT_ID:'p2',DODO_STARTER_CREDITS:'100',DODO_SCALE_CREDITS:'500',RUN_CREDIT_COST:'10',DODO_RETURN_URL:'https://return.test',GITHUB_WEBHOOK_SECRET:'test-secret'} as any)
const setup=()=>{const billingStore=new MemoryBillingStore(); const provider:any={createCheckout:async()=>({id:'c',url:'https://checkout.test'}),verifyWebhook:async()=>({kind:'activated',id:'evt',email:'a@b.com',customerId:'cus',subscriptionId:'sub',productId:'p1',grantKey:'period'})}; return {billingStore,app:createApp({config,store:new MemoryRunStore(),events:new InMemoryEventBus(),users:new MemoryUserStore(),billing:{provider,store:billingStore,catalog}})}}
describe('billing routes',()=>{it('publishes plans without product ids and creates checkout',async()=>{const {app}=setup(); const plans=await (await app.request('/v1/billing/plans')).json() as any; expect(plans.plans[0]).not.toHaveProperty('productId'); const r=await app.request('/v1/billing/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({plan:'starter',email:'A@B.COM'})}); expect(r.status).toBe(201)})
it('applies duplicate webhooks once',async()=>{const {app,billingStore}=setup(); for(let i=0;i<2;i++) expect((await app.request('/v1/billing/webhooks/dodo',{method:'POST',body:'raw'})).status).toBe(200); expect((await billingStore.getAccount('a@b.com'))?.balance.granted).toBe(100)})
it('requires credits for billed runs',async()=>{const {app}=setup(); const r=await app.request('/v1/runs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({mode:'discovery',targetUrl:'https://example.com',email:'none@example.com'})}); expect(r.status).toBe(402)})
it('does not let GitHub webhooks bypass billing identity and credits',async()=>{const {app}=setup();const body=JSON.stringify({action:'opened',repository:{full_name:'acme/app'},pull_request:{number:7,head:{sha:'head'},base:{sha:'base'}}});const signature=`sha256=${createHmac('sha256','test-secret').update(body).digest('hex')}`;const response=await app.request('/v1/github/webhook',{method:'POST',headers:{'x-hub-signature-256':signature,'x-github-event':'pull_request','x-freebug-target-url':'https://preview.example.com'},body});expect(response.status).toBe(402);expect(await response.json()).toEqual({error:'billing_account_required'})})})
