import { normalizeAccountKey,type BillingAccount,type CreditBalance,type SubscriptionStatus } from './domain.js'
export interface SubscriptionUpdate {accountKey?:string;email:string;customerId:string;subscriptionId:string;plan:'starter'|'scale';status:SubscriptionStatus}
export interface BillingStore {getAccount(key:string):Promise<BillingAccount|undefined>;upsertSubscription(input:SubscriptionUpdate):Promise<BillingAccount>;grantCredits(input:{accountKey:string;amount:number;idempotencyKey:string}):Promise<boolean>;reserveCredits(input:{accountKey:string;amount:number;reservationId:string}):Promise<boolean>;settleReservation(id:string):Promise<boolean>;releaseReservation(id:string):Promise<boolean>}
type RecordValue={account:Omit<BillingAccount,'balance'>;granted:number;consumed:number;reservations:Map<string,{amount:number;state:'reserved'|'settled'|'released'}>}
export class MemoryBillingStore implements BillingStore { private records=new Map<string,RecordValue>(); private grants=new Set<string>(); private queue=Promise.resolve()
 private atomic<T>(fn:()=>T|Promise<T>){const result=this.queue.then(fn,fn);this.queue=result.then(()=>undefined,()=>undefined);return result} private balance(record:RecordValue):CreditBalance{let reserved=0;for(const item of record.reservations.values())if(item.state==='reserved')reserved+=item.amount;return{granted:record.granted,consumed:record.consumed,reserved,available:record.granted-record.consumed-reserved}}
 async getAccount(key:string){const record=this.records.get(normalizeAccountKey(key));return record?{...record.account,balance:this.balance(record)}:undefined}
 upsertSubscription(input:SubscriptionUpdate){return this.atomic(()=>{const key=normalizeAccountKey(input.accountKey??input.email),record=this.records.get(key)??{account:{accountKey:key,email:key},granted:0,consumed:0,reservations:new Map()};record.account={...record.account,...input,accountKey:key,email:normalizeAccountKey(input.email)};this.records.set(key,record);return{...record.account,balance:this.balance(record)}})}
 grantCredits(input:{accountKey:string;amount:number;idempotencyKey:string}){return this.atomic(()=>{this.validate(input.amount);if(this.grants.has(input.idempotencyKey))return false;const record=this.records.get(normalizeAccountKey(input.accountKey));if(!record)throw new Error('account_not_found');record.granted+=input.amount;this.grants.add(input.idempotencyKey);return true})}
 reserveCredits(input:{accountKey:string;amount:number;reservationId:string}){return this.atomic(()=>{this.validate(input.amount);const record=this.records.get(normalizeAccountKey(input.accountKey));if(!record||this.balance(record).available<input.amount||record.reservations.has(input.reservationId))return false;record.reservations.set(input.reservationId,{amount:input.amount,state:'reserved'});return true})}
 private transition(id:string,state:'settled'|'released'){return this.atomic(()=>{for(const record of this.records.values()){const reservation=record.reservations.get(id);if(reservation?.state==='reserved'){reservation.state=state;if(state==='settled')record.consumed+=reservation.amount;return true}}return false})} settleReservation(id:string){return this.transition(id,'settled')} releaseReservation(id:string){return this.transition(id,'released')} private validate(amount:number){if(!Number.isInteger(amount)||amount<=0)throw new Error('invalid_credit_amount')}
}
